export type ShelfKind = "book" | "album" | "movie";
export type ShelfRating = 0.5 | 1 | 1.5 | 2 | 2.5 | 3 | 3.5 | 4 | 4.5 | 5;

export type ShelfItem = {
  creator: string;
  href: string;
  id: string;
  image: string;
  kind: ShelfKind;
  rating?: ShelfRating;
  title: string;
  year: string;
};

export const shelfSections = [
  {
    description:
      "These are the books that stayed with me after I put them down. A few changed how I think; others are here because I loved the story.",
    id: "books",
    kind: "book",
    title: "books",
  },
  {
    description:
      "I can't go a day without listening to music, usually while doing something else. Not constantly, because it can get distracting, but I have to put something on at least once.",
    id: "music",
    kind: "album",
    title: "music",
  },
  {
    description:
      "Movies are the part of this page I expect to change most. I keep remembering old favorites, then finding new ones I want to add.",
    id: "movies",
    kind: "movie",
    title: "movies",
  },
] as const satisfies ReadonlyArray<{
  description: string;
  id: string;
  kind: ShelfKind;
  title: string;
}>;

export const shelfItems = [
  {
    creator: "Brian Christian and Tom Griffiths",
    href: "https://openlibrary.org/isbn/9781627790369",
    id: "algorithms-to-live-by",
    image: "/shelf/books/algorithms-to-live-by.jpg",
    kind: "book",
    title: "Algorithms to Live By",
    year: "2016",
  },
  {
    creator: "J. D. Salinger",
    href: "https://openlibrary.org/isbn/9780316769174",
    id: "the-catcher-in-the-rye",
    image: "/shelf/books/the-catcher-in-the-rye.jpg",
    kind: "book",
    rating: 4,
    title: "The Catcher in the Rye",
    year: "1951",
  },
  {
    creator: "Leo Tolstoy",
    href: "https://openlibrary.org/isbn/9780140449174",
    id: "anna-karenina",
    image: "/shelf/books/anna-karenina.jpg",
    kind: "book",
    rating: 3,
    title: "Anna Karenina",
    year: "1878",
  },
  {
    creator: "Daniel Kahneman",
    href: "https://openlibrary.org/isbn/9780374533557",
    id: "thinking-fast-and-slow",
    image: "/shelf/books/thinking-fast-and-slow.jpg",
    kind: "book",
    title: "Thinking, Fast and Slow",
    year: "2011",
  },
  {
    creator: "Jim Collins",
    href: "https://openlibrary.org/isbn/9780066620992",
    id: "good-to-great",
    image: "/shelf/books/good-to-great.jpg",
    kind: "book",
    title: "Good to Great",
    year: "2001",
  },
  {
    creator: "Yuval Noah Harari",
    href: "https://openlibrary.org/isbn/9780062316097",
    id: "sapiens",
    image: "/shelf/books/sapiens.jpg",
    kind: "book",
    title: "Sapiens",
    year: "2011",
  },
  {
    creator: "Clayton M. Christensen",
    href: "https://openlibrary.org/isbn/9781633691780",
    id: "the-innovators-dilemma",
    image: "/shelf/books/the-innovators-dilemma.jpg",
    kind: "book",
    title: "The Innovator's Dilemma",
    year: "1997",
  },
  {
    creator: "Stevie Wonder",
    href: "https://open.spotify.com/album/5jgI8Eminx9MmLBontDWq8",
    id: "innervisions",
    image: "/shelf/albums/innervisions.jpg",
    kind: "album",
    title: "Innervisions",
    year: "1973",
  },
  {
    creator: "Stevie Wonder",
    href: "https://open.spotify.com/album/7CHbtqCFJhRwQ6I3Smf74c",
    id: "songs-in-the-key-of-life",
    image: "/shelf/albums/songs-in-the-key-of-life.jpg",
    kind: "album",
    title: "Songs in the Key of Life",
    year: "1976",
  },
  {
    creator: "Earth, Wind & Fire",
    href: "https://open.spotify.com/album/0w0eT42Gyq6G9yXB0RirWh",
    id: "all-n-all",
    image: "/shelf/albums/all-n-all.jpg",
    kind: "album",
    title: "All 'N All",
    year: "1977",
  },
  {
    creator: "Billy Joel",
    href: "https://open.spotify.com/album/1Mhn9VosyjtWn4dMPFlna6",
    id: "the-stranger",
    image: "/shelf/albums/the-stranger.jpg",
    kind: "album",
    title: "The Stranger (Legacy Edition)",
    year: "1977",
  },
  {
    creator: "Billy Joel",
    href: "https://open.spotify.com/album/1HmCO8VK98AU6EXPOjGYyI",
    id: "52nd-street",
    image: "/shelf/albums/52nd-street.jpg",
    kind: "album",
    title: "52nd Street",
    year: "1978",
  },
  {
    creator: "Earth, Wind & Fire",
    href: "https://open.spotify.com/album/33qllbBGuRxXO4a28u2fc6",
    id: "i-am",
    image: "/shelf/albums/i-am.jpg",
    kind: "album",
    title: "I Am",
    year: "1979",
  },
  {
    creator: "Michael Jackson",
    href: "https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ",
    id: "thriller",
    image: "/shelf/albums/thriller.jpg",
    kind: "album",
    title: "Thriller",
    year: "1982",
  },
  {
    creator: "Prince",
    href: "https://open.spotify.com/album/2qSwmENEVYoacaxatupAaE",
    id: "purple-rain",
    image: "/shelf/albums/purple-rain.jpg",
    kind: "album",
    title: "Purple Rain",
    year: "1984",
  },
  {
    creator: "Sade",
    href: "https://open.spotify.com/album/4wCvCNsMJJvyeX5mGO40ae",
    id: "promise",
    image: "/shelf/albums/promise.jpg",
    kind: "album",
    title: "Promise",
    year: "1985",
  },
  {
    creator: "Luther Vandross",
    href: "https://open.spotify.com/album/20okHMjdnVL1rDtgPo81vY",
    id: "the-night-i-fell-in-love",
    image: "/shelf/albums/the-night-i-fell-in-love.jpg",
    kind: "album",
    title: "The Night I Fell in Love",
    year: "1985",
  },
  {
    creator: "Prince",
    href: "https://open.spotify.com/album/1XsXHctYSQNyAd9BANCk2B",
    id: "sign-o-the-times",
    image: "/shelf/albums/sign-o-the-times.jpg",
    kind: "album",
    rating: 5,
    title: "Sign o' the Times",
    year: "1987",
  },
  {
    creator: "Michael Jackson",
    href: "https://open.spotify.com/album/10sRGSw8yIKgiOTJoUZRfI",
    id: "bad",
    image: "/shelf/albums/bad.jpg",
    kind: "album",
    title: "Bad",
    year: "1987",
  },
  {
    creator: "Mariah Carey",
    href: "https://open.spotify.com/album/0SHpIbyBLUugMXsl3yNkUz",
    id: "emotions",
    image: "/shelf/albums/emotions.jpg",
    kind: "album",
    title: "Emotions",
    year: "1991",
  },
  {
    creator: "Luis Miguel",
    href: "https://open.spotify.com/album/4MjzdTkEmTwPAlVwDSSivP",
    id: "romance",
    image: "/shelf/albums/romance.jpg",
    kind: "album",
    title: "Romance",
    year: "1991",
  },
  {
    creator: "Michael Jackson",
    href: "https://open.spotify.com/album/0oX4SealMgNXrvRDhqqOKg",
    id: "dangerous",
    image: "/shelf/albums/dangerous-original.jpg",
    kind: "album",
    rating: 5,
    title: "Dangerous",
    year: "1991",
  },
  {
    creator: "Selena",
    href: "https://open.spotify.com/album/02fBX9fLFfOG2v33oZo73z",
    id: "entre-a-mi-mundo",
    image: "/shelf/albums/entre-a-mi-mundo.jpg",
    kind: "album",
    title: "Entre a Mi Mundo",
    year: "1992",
  },
  {
    creator: "Prince",
    href: "https://open.spotify.com/album/5q8jywtY8AvpUVgzDJXyRp",
    id: "love-symbol",
    image: "/shelf/albums/love-symbol.jpg",
    kind: "album",
    title: "[Love Symbol]",
    year: "1992",
  },
  {
    creator: "Selena",
    href: "https://open.spotify.com/album/03KrSnWTEWdt5iE857UoIu",
    id: "amor-prohibido",
    image: "/shelf/albums/amor-prohibido.jpg",
    kind: "album",
    title: "Amor Prohibido",
    year: "1994",
  },
  {
    creator: "Sade",
    href: "https://open.spotify.com/album/4tYiiSjPEguQYzSMne1HfX",
    id: "the-best-of-sade",
    image: "/shelf/albums/the-best-of-sade.jpg",
    kind: "album",
    title: "The Best of Sade",
    year: "1994",
  },
  {
    creator: "2Pac",
    href: "https://open.spotify.com/album/5ASoLiKB7ffqusD9X9wQlS",
    id: "me-against-the-world",
    image: "/shelf/albums/me-against-the-world.jpg",
    kind: "album",
    title: "Me Against the World",
    year: "1995",
  },
  {
    creator: "2Pac",
    href: "https://open.spotify.com/album/1Mdy7hhoQRYdVrHzYnlUee",
    id: "all-eyez-on-me",
    image: "/shelf/albums/all-eyez-on-me.jpg",
    kind: "album",
    title: "All Eyez on Me",
    year: "1996",
  },
  {
    creator: "Mariah Carey",
    href: "https://open.spotify.com/album/7aDBFWp72Pz4NZEtVBANi9",
    id: "butterfly",
    image: "/shelf/albums/butterfly.jpg",
    kind: "album",
    title: "Butterfly",
    year: "1997",
  },
  {
    creator: "Luis Miguel",
    href: "https://open.spotify.com/album/3OdgRM6jaoh8Q1Nu3BnheU",
    id: "romances",
    image: "/shelf/albums/romances.jpg",
    kind: "album",
    title: "Romances",
    year: "1997",
  },
  {
    creator: "George Michael",
    href: "https://open.spotify.com/album/0IJcpy0eM4o63J43qij68g",
    id: "ladies-and-gentlemen",
    image: "/shelf/albums/ladies-and-gentlemen.jpg",
    kind: "album",
    title: "Ladies & Gentlemen: The Best of George Michael",
    year: "1998",
  },
  {
    creator: "D'Angelo",
    href: "https://open.spotify.com/album/5mwC516GzRfwwkx7mYANxY",
    id: "voodoo",
    image: "/shelf/albums/voodoo.jpg",
    kind: "album",
    title: "Voodoo",
    year: "2000",
  },
  {
    creator: "Drake",
    href: "https://open.spotify.com/album/0NGwRz0semIXUCSxR0uffa",
    id: "take-care",
    image: "/shelf/albums/take-care.jpg",
    kind: "album",
    title: "Take Care",
    year: "2011",
  },
  {
    creator: "Kendrick Lamar",
    href: "https://open.spotify.com/album/6PBZN8cbwkqm1ERj2BGXJ1",
    id: "good-kid-maad-city",
    image: "/shelf/albums/good-kid-maad-city.jpg",
    kind: "album",
    title: "good kid, m.A.A.d city",
    year: "2012",
  },
  {
    creator: "Bruno Mars",
    href: "https://open.spotify.com/album/4PgleR09JVnm3zY1fW3XBA",
    id: "24k-magic",
    image: "/shelf/albums/24k-magic.jpg",
    kind: "album",
    title: "24K Magic",
    year: "2016",
  },
  {
    creator: "Anderson .Paak",
    href: "https://open.spotify.com/album/6xNFuLOko8gjxi5kUAyGyM",
    id: "malibu",
    image: "/shelf/albums/malibu.jpg",
    kind: "album",
    title: "Malibu",
    year: "2016",
  },
  {
    creator: "Anderson .Paak",
    href: "https://open.spotify.com/album/0YF8PfcGbsKg5IaFyPnlyY",
    id: "ventura",
    image: "/shelf/albums/ventura.jpg",
    kind: "album",
    title: "Ventura",
    year: "2019",
  },
  {
    creator: "ScHoolboy Q",
    href: "https://open.spotify.com/album/107WsrBqn5xVPgystkziry",
    id: "blue-lips",
    image: "/shelf/albums/blue-lips.jpg",
    kind: "album",
    title: "BLUE LIPS",
    year: "2024",
  },
  {
    creator: "NxWorries",
    href: "https://open.spotify.com/album/0LlzHi8Erl8zpTumqt88Qe",
    id: "why-lawd",
    image: "/shelf/albums/why-lawd.jpg",
    kind: "album",
    title: "Why Lawd?",
    year: "2024",
  },
  {
    creator: "Bruno Mars",
    href: "https://open.spotify.com/album/7vI4iTxDmgEN63liQHPEX1",
    id: "the-romantic",
    image: "/shelf/albums/the-romantic.jpg",
    kind: "album",
    title: "The Romantic",
    year: "2026",
  },
  {
    creator: "Francis Ford Coppola",
    href: "https://www.themoviedb.org/movie/238-the-godfather",
    id: "the-godfather",
    image: "/shelf/movies/the-godfather.jpg",
    kind: "movie",
    title: "The Godfather",
    year: "1972",
  },
  {
    creator: "Brian De Palma",
    href: "https://www.themoviedb.org/movie/111-scarface",
    id: "scarface",
    image: "/shelf/movies/scarface.jpg",
    kind: "movie",
    title: "Scarface",
    year: "1983",
  },
  {
    creator: "Albert Magnoli",
    href: "https://www.themoviedb.org/movie/13763-purple-rain",
    id: "purple-rain-movie",
    image: "/shelf/movies/purple-rain.jpg",
    kind: "movie",
    title: "Purple Rain",
    year: "1984",
  },
  {
    creator: "Peter Weir",
    href: "https://www.themoviedb.org/movie/207-dead-poets-society",
    id: "dead-poets-society",
    image: "/shelf/movies/dead-poets-society.jpg",
    kind: "movie",
    title: "Dead Poets Society",
    year: "1989",
  },
  {
    creator: "Martin Scorsese",
    href: "https://www.themoviedb.org/movie/769-goodfellas",
    id: "goodfellas",
    image: "/shelf/movies/goodfellas.jpg",
    kind: "movie",
    title: "GoodFellas",
    year: "1990",
  },
  {
    creator: "Robert De Niro",
    href: "https://www.themoviedb.org/movie/1607-a-bronx-tale",
    id: "a-bronx-tale",
    image: "/shelf/movies/a-bronx-tale.jpg",
    kind: "movie",
    title: "A Bronx Tale",
    year: "1993",
  },
  {
    creator: "Quentin Tarantino",
    href: "https://www.themoviedb.org/movie/680-pulp-fiction",
    id: "pulp-fiction",
    image: "/shelf/movies/pulp-fiction.jpg",
    kind: "movie",
    title: "Pulp Fiction",
    year: "1994",
  },
  {
    creator: "Frank Darabont",
    href: "https://www.themoviedb.org/movie/278-the-shawshank-redemption",
    id: "the-shawshank-redemption",
    image: "/shelf/movies/the-shawshank-redemption.jpg",
    kind: "movie",
    title: "The Shawshank Redemption",
    year: "1994",
  },
  {
    creator: "F. Gary Gray",
    href: "https://www.themoviedb.org/movie/10634-friday",
    id: "friday",
    image: "/shelf/movies/friday.jpg",
    kind: "movie",
    title: "Friday",
    year: "1995",
  },
  {
    creator: "Michael Mann",
    href: "https://www.themoviedb.org/movie/949-heat",
    id: "heat",
    image: "/shelf/movies/heat.jpg",
    kind: "movie",
    title: "Heat",
    year: "1995",
  },
  {
    creator: "Peter Weir",
    href: "https://www.themoviedb.org/movie/37165-the-truman-show",
    id: "the-truman-show",
    image: "/shelf/movies/the-truman-show.jpg",
    kind: "movie",
    title: "The Truman Show",
    year: "1998",
  },
  {
    creator: "Lana and Lilly Wachowski",
    href: "https://www.themoviedb.org/movie/603-the-matrix",
    id: "the-matrix",
    image: "/shelf/movies/the-matrix.jpg",
    kind: "movie",
    title: "The Matrix",
    year: "1999",
  },
  {
    creator: "David Fincher",
    href: "https://www.themoviedb.org/movie/550-fight-club",
    id: "fight-club",
    image: "/shelf/movies/fight-club.jpg",
    kind: "movie",
    title: "Fight Club",
    year: "1999",
  },
  {
    creator: "Mary Harron",
    href: "https://www.themoviedb.org/movie/1359-american-psycho",
    id: "american-psycho",
    image: "/shelf/movies/american-psycho.jpg",
    kind: "movie",
    title: "American Psycho",
    year: "2000",
  },
  {
    creator: "Brett Ratner",
    href: "https://www.themoviedb.org/movie/5175-rush-hour-2",
    id: "rush-hour-2",
    image: "/shelf/movies/rush-hour-2.jpg",
    kind: "movie",
    title: "Rush Hour 2",
    year: "2001",
  },
  {
    creator: "Larry Charles",
    href: "https://www.themoviedb.org/movie/496-borat-cultural-learnings-of-america-for-make-benefit-glorious-nation-of-kazakhstan",
    id: "borat",
    image: "/shelf/movies/borat.jpg",
    kind: "movie",
    title: "Borat",
    year: "2006",
  },
  {
    creator: "Brian Robbins",
    href: "https://www.themoviedb.org/movie/9757-norbit",
    id: "norbit",
    image: "/shelf/movies/norbit.jpg",
    kind: "movie",
    title: "Norbit",
    year: "2007",
  },
  {
    creator: "Greg Mottola",
    href: "https://www.themoviedb.org/movie/8363-superbad",
    id: "superbad",
    image: "/shelf/movies/superbad.jpg",
    kind: "movie",
    rating: 4,
    title: "Superbad",
    year: "2007",
  },
  {
    creator: "Todd Phillips",
    href: "https://www.themoviedb.org/movie/18785-the-hangover",
    id: "the-hangover",
    image: "/shelf/movies/the-hangover.jpg",
    kind: "movie",
    rating: 4.5,
    title: "The Hangover",
    year: "2009",
  },
  {
    creator: "David Fincher",
    href: "https://www.themoviedb.org/movie/37799-the-social-network",
    id: "the-social-network",
    image: "/shelf/movies/the-social-network.jpg",
    kind: "movie",
    title: "The Social Network",
    year: "2010",
  },
  {
    creator: "Martin Scorsese",
    href: "https://www.themoviedb.org/movie/106646-the-wolf-of-wall-street",
    id: "the-wolf-of-wall-street",
    image: "/shelf/movies/the-wolf-of-wall-street.jpg",
    kind: "movie",
    title: "The Wolf of Wall Street",
    year: "2013",
  },
  {
    creator: "Damien Chazelle",
    href: "https://www.themoviedb.org/movie/244786-whiplash",
    id: "whiplash",
    image: "/shelf/movies/whiplash.jpg",
    kind: "movie",
    title: "Whiplash",
    year: "2014",
  },
  {
    creator: "Christopher Nolan",
    href: "https://www.themoviedb.org/movie/157336-interstellar",
    id: "interstellar",
    image: "/shelf/movies/interstellar.jpg",
    kind: "movie",
    title: "Interstellar",
    year: "2014",
  },
  {
    creator: "Robert Zemeckis",
    href: "https://www.themoviedb.org/movie/369885-allied",
    id: "allied",
    image: "/shelf/movies/allied.jpg",
    kind: "movie",
    rating: 4,
    title: "Allied",
    year: "2016",
  },
  {
    creator: "Jordan Peele",
    href: "https://www.themoviedb.org/movie/419430-get-out",
    id: "get-out",
    image: "/shelf/movies/get-out.jpg",
    kind: "movie",
    rating: 4,
    title: "Get Out",
    year: "2017",
  },
  {
    creator: "Bong Joon Ho",
    href: "https://www.themoviedb.org/movie/496243-parasite",
    id: "parasite",
    image: "/shelf/movies/parasite.jpg",
    kind: "movie",
    title: "Parasite",
    year: "2019",
  },
] satisfies ShelfItem[];

const featuredShelfItemIds = [
  "algorithms-to-live-by",
  "purple-rain",
  "the-godfather",
  "thinking-fast-and-slow",
  "thriller",
  "the-wolf-of-wall-street",
] as const;

export const featuredShelfItems = featuredShelfItemIds.map((id) => {
  const item = shelfItems.find((shelfItem) => shelfItem.id === id);

  if (!item) {
    throw new Error(`Missing featured shelf item: ${id}`);
  }

  return item;
});
